### ISSUE TITLE
https://next-auth.js.org/errors#signin_oauth_error getaddrinfo ENOTFOUND KEYCLOAK_HOST

### ISSUE THREAD

**Issue by skoulouzis** [QCDIS/VREPaaS#137]
The root cause of this error seems to be that the application attempted to perform a DNS lookup for the hostname "KEYCLOAK_HOST," but the DNS resolution failed because the hostname could not be found in the DNS system.

This could be related to minikube ingress https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

**Comment by skoulouzis** [comment]
Running :
```
minikube dashboard
```
and login into the vrepaas-vreapp pod we run:

```
wget google.com
```

We get:
```
wget: bad address 'google.com'
```
instead of:
```
--2023-09-11 12:51:10--  http://google.com/
Resolving google.com (google.com)... 142.250.186.174, 2a00:1450:4001:810::200e
Connecting to google.com (google.com)|142.250.186.174|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://www.google.com/ [following]
--2023-09-11 12:51:10--  http://www.google.com/
Resolving www.google.com (www.google.com)... 172.217.16.196, 2a00:1450:4001:812::2004
Connecting to www.google.com (www.google.com)|172.217.16.196|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html’

index.html                                 [ <=>                                                                         ]  20.24K  --.-KB/s    in 0.08s   

2023-09-11 12:51:11 (242 KB/s) - ‘index.html’ saved [20722]

```

**Comment by skoulouzis** [comment]
When removing the line:
```
dns=dnsmasq
``` 
from /etc/NetworkManager/NetworkManager.conf deleting /etc/NetworkManager/dnsmasq.d/ and restarting the Network Manager:
```
systemctl restart NetworkManager.service
```
and logging in to the vrepaas-vreapp pod and typing:
```
/app # wget google.com
Connecting to google.com (142.250.186.78:80)
Connecting to www.google.com (142.250.185.132:80)
saving to 'index.html'
index.html           100% |********************************| 20765  0:00:00 ETA
'index.html' saved
```

**Comment by gpelouze** [comment]
"Works on my laptop, cannot replicate"

**Comment by gpelouze** [comment]
@skoulouzis if you’re on Ubuntu 22.04, the DNS is probably managed by systemd-resolved instead of NetworkManager. Does using this setup help: https://github.com/QCDIS/NaaVRE-dev-environment#minikube-cluster?
